# Generated by Django 3.1.3 on 2023-08-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='questions',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='enrollement_id',
            new_name='enrollment',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='choice_id',
        ),
        migrations.AddField(
            model_name='question',
            name='grade',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='submission',
            name='choices',
            field=models.ManyToManyField(to='onlinecourse.Choice'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(default='choice text', max_length=300),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(default='question text', max_length=400),
        ),
    ]
